# Generated by Django 4.2.5 on 2023-11-20 09:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('indicators', '0003_indicatordata_answer_choice_comm_stability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatordata',
            name='answer_choice_comm_stability',
            field=models.CharField(blank=True, choices=[('', 'Select an answer'), ('Very much', 'Very much'), ('Not at all', 'Not at all')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='SatisfactionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfaction_services', models.CharField(blank=True, choices=[('', 'Select a service'), ('Improved seeds supply', 'Improved seeds supply'), ('Training on innovation farming/agricultural techniques', 'Training on innovation farming/agricultural techniques'), ('Agricultural machines (e.g. tractors, cultivators, fertilizer spreader)', 'Agricultural machines (e.g. tractors, cultivators, fertiliser spreader)'), ('Fertilizers/herbicides', 'Fertilizers/herbicides'), ('Processing facilities', 'Processing facilities'), ('Advice on innovation farming/agricultural techniques', 'Advice on innovation farming/agricultural techniques'), ('Financial loans', 'Financial loans')], max_length=100, null=True)),
                ('indicator_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10)),
                ('date_submitted', models.DateField(default=django.utils.timezone.now)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.district')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.indicator')),
            ],
            options={
                'verbose_name_plural': 'Satisfaction Data',
            },
        ),
    ]
