# Generated by Django 4.2.5 on 2023-11-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0004_alter_indicatordata_answer_choice_comm_stability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satisfactiondata',
            name='satisfaction_services',
            field=models.CharField(blank=True, choices=[('', 'Select a service'), ('Improved seeds supply', 'Improved seeds supply'), ('Training on farming techniques', 'Training on farming techniques'), ('Agricultural machines', 'Agricultural machines'), ('Fertilizers', 'Fertilizers'), ('Processing facilities', 'Processing facilities'), ('Advice on farming techniques', 'Advice on farming techniques'), ('Financial loans', 'Financial loans')], max_length=100, null=True),
        ),
    ]
